name: Build KImageFormats
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-20.04, macos-latest]
        vers: ['5.15.2']
        forceWin32: ['false']
        include:
          - os: windows-2019
            vers: '5.15.2'
            forceWin32: 'true'
          - os: windows-2019
            vers: '6.2.2'
            forceWin32: 'false'
          - os: macos-latest
            vers: '6.2.2'
            forceWin32: 'false'

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.vers }}
          arch: ${{ matrix.forceWin32 != 'true' && 'win64_msvc2019_64' || 'win32_msvc2019' }}

      - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: 'c2e8ba09ce99ae9b3f5c720bbe93da860575193e'

      - name: Build KImageFormats (just one big step for now)
        run: pwsh pwsh/buildkimageformats.ps1
        env:
          forceWin32: ${{ matrix.forceWin32 }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: kimageformats-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.vers }}-${{ matrix.forceWin32 }}
          path: ${{ github.workspace }}/kimageformats/bin/
