name: Build KImageFormats
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        vers: ['5.15.2']

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.vers }}
          

      - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: 'c2e8ba09ce99ae9b3f5c720bbe93da860575193e'

      - name: Build KImageFormats (just one big step for now)
        run: pwsh pwsh/buildkimageformats.ps1

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: kimageformats-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.vers }}
          path: ${{ github.workspace }}/kimageformats/bin/
