name: Build KImageFormats
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'

      - name: Build KImageFormats (just one big step for now)
        run: pwsh/buildkimageformats.ps1
        
