name: Build qt-heic-image-plugin
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        vers: ['5.15.2']

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.vers }}

      - name: Build qt-heic-image-plugin
        run: pwsh pwsh/buildheic.ps1

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: qtheic-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.vers }}
          path: ${{ github.workspace }}/qt-heic-image-plugin/qtbuild_5.15.2/plugins/
