name: Build qt-heic-image-plugin
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        vers: ['5.15.2']
        include:
          - os: windows-2019
            vers: '5.15.2'
            forceWin32: 'true'
            arch: 'win64_msvc2019_64'
          - os: windows-2019
            vers: '6.2.2'
            forceWin32: 'false'
            arch: 'win32_msvc2019'

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.vers }}
          arch: ${{ matrix.arch }}

      - name: Build qt-heic-image-plugin
        run: pwsh pwsh/buildheic.ps1
        env:
          forceWin32: ${{ matrix.forceWin32 }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: qtheic-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.vers }}-${{ matrix.forceWin32 }}
          path: ${{ github.workspace }}/qt-heic-image-plugin/qtbuild_5.15.2/plugins/
