name: Build QtApng
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        vers: ['5.15.2'],
        forceWin32: ['false']
        include:
          - vers: '5.15.2'
            os: windows-2019
            forceWin32: true
          - vers: '6.2.1'
            os: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.vers }}

      - name: Build QtApng
        run: pwsh pwsh/buildapng.ps1
        env:
          forceWin32: ${{ matrix.forceWin32 }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: qtapng-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.vers }}
          path: ${{ github.workspace }}/QtApng/plugins
