name: Build QtApng
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11, windows-2019]
        vers: ['5.15.2']
        forceWin32: ['false']
        include:
          - os: windows-2019
            vers: '5.15.2'
            forceWin32: 'true'
          - os: macos-11
            vers: '6.2.2'
            forceWin32: 'false'

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.vers }}
          arch: ${{ matrix.forceWin32 != 'true' && 'win64_msvc2019_64' || 'win32_msvc2019' }}

      - name: Build QtApng
        run: pwsh pwsh/buildapng.ps1
        env:
          forceWin32: ${{ matrix.forceWin32 }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: qtapng-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.vers }}-${{ matrix.forceWin32 }}
          path: ${{ github.workspace }}/QtApng/plugins
